### ISSUE TITLE
Autocomplete should work on searches beyond the first one

### ISSUE THREAD

**Issue by robgur** [MapofLife/MOL#101]
Right now, autocomplete only works when you first search.  Subsequent searches (at least on Chrome) don't have autocompletion.

**Comment by eightysteele** [comment]
Are you testing this on localhost or canary? If canary, we're bulkloading autocompletes there, so it'll be unstable for a bit.

**Comment by robgur** [comment]
Yeah canary... good to know.

**Comment by eightysteele** [comment]
I'll send out a message, but generally canary is unstable. Closing issue.
