### ISSUE TITLE
loader.py memory management

### ISSUE THREAD

**Issue by eightysteele** [MapofLife/MOL#11]
loader.py stores GeoJSON features in a all_features list. When processing many shapefiles this gets too big and the program exits.

**Comment by gaurav** [comment]
I'm planning to work on this tomorrow.

**Comment by eightysteele** [comment]
Solved via file streaming. Will push.
On Nov 11, 2011 11:42 AM, "Gaurav Vaidya" <
reply@reply.github.com>
wrote:
