### ISSUE TITLE
Make a color/style picker widget for map layers. 

### ISSUE THREAD

**Issue by jmalczyk** [MapofLife/MOL#124]
We need a little pop-up styler that allows the user to choose some map styles to apply to a layer. It just needs to generate some cartoCSS and apply it using the "apply-layer-style" event in mol.map.tiles.js.

**Comment by tomauer** [comment]
I'm going to start working on this for longer term.

**Comment by tomauer** [comment]
Where and what was listening for the 'apply-layer-style' event?

**Comment by jmalczyk** [comment]
mol.map.tile.js -- the module that handles adding tile layers through the
gmaps api.

**Comment by tomauer** [comment]
This has been merged into develop. Closing this issue.
