### ISSUE TITLE
Get default layer opacity and style from the database.

### ISSUE THREAD

**Issue by jmalczyk** [MapofLife/MOL#125]
Default opacities are hard coded according to layer type in javascript. Default styles are also hard coded there via selection of a cartodb table that has the styles assigned to it (style_table).
All of this style should be registered to datasets, types, and providers in the database and pulled from there by the search widget when layer metadata is initially retrieved..

**Comment by tomauer** [comment]
The opacities part of this is apparently taken care of.

**Comment by tomauer** [comment]
Has been handled in the recent layer widget merge.
