### ISSUE TITLE
Linking directly to a search doesn't work for me

### ISSUE THREAD

**Issue by gaurav** [MapofLife/MOL#193]
I've tried accessing http://www.mappinglife.org/Socratea%20exorrhiza (the URL mentioned in our April blog post) on Firefox, Safari and Opera on the Mac, and couldn't get it to work: it won't display the splash dialog, but it won't start the search either. Is this just a Mac thing maybe?

**Comment by robgur** [comment]
looks like its broken....

**Comment by jmalczyk** [comment]
Yes, it is broken for that species. I'll look into it.

**Comment by jmalczyk** [comment]
Fixed this in 37a6d85cf21a62d1d9bc0c12b5a338b0d105174c
