### ISSUE TITLE
Accounting of existing data in the MoL system

### ISSUE THREAD

**Issue by gaurav** [MapofLife/MOL#26]
An accounting of our current data assets and _exactly_ where they are and in what form.  This includes all range maps , ecoregions, point occurrence data sets, assemblage checklists datasets.  I have been asking for this accounting for a long time and I think it is nigh due.  

In our effort to provision more data into MoL, please also take a look here: http://esp.cr.usgs.gov/data/atlas/little/.  

I can see how to get individual shape files via "click and download" but annoyingly, there is no full distribution available.  Can we check about feasibility of getting all these shapefiles in MoL?

**Comment by gaurav** [comment]
Don't upload them without verifying.

**Comment by eightysteele** [comment]
Can we just start this using a Google Spreadsheet for now?

**Comment by gaurav** [comment]
I've done that, but I need some way of summarizing information across either a directory of shapefiles, or (more easily) across CartoDB. That's why I asked whether we're eventually going to need that sort of functionality on the main website; otherwise, I could just throw together some scripts to generate those numbers. But they are definitely going into a Google Spreadsheet (just e-mailed it to you again right now).

**Comment by eightysteele** [comment]
Yeah man, I think just some scripts for now? Is that good enough? Thanks for sending the spreadsheet again.
