### ISSUE TITLE
Replace customized cartodb-gmapsv3.js 

### ISSUE THREAD

**Issue by eightysteele** [MapofLife/MOL#32]
We previously hacked `app/js/lib/cartodb-gmapsv3.js` to work with our CartoDB instance running on Linode. Let's yank that out and replace it with the version in use by our hosted CartoDB instance. Note that `mol.map.tiles.js` will need to be updated.

**Comment by jmalczyk** [comment]
Fixed by commit 23f58d30448b0fb8563dc5b151f5b6a2c3df6cd1

**Comment by eightysteele** [comment]
LGTM. Also, here's a good style guide for commit messages:

https://github.com/erlang/otp/wiki/Writing-good-commit-messages
