### ISSUE TITLE
Add search term/result caching

### ISSUE THREAD

**Issue by eightysteele** [MapofLife/MOL#39]
We need to start caching search results in the UI.

**Comment by jmalczyk** [comment]
The autocomplete widget already gets a complete list of what is available when the app initializes to populate its source array. There's no reason source and type metadata couldn't come with it to speed up the layer search.

**Comment by eightysteele** [comment]
> The autocomplete widget already gets a complete list of what is available when the app initializes

Explain more. Are you saying it grabs a distinct list of all scientific names from the `polygons` and `points` table?

**Comment by jmalczyk** [comment]
Yes, it gets a distinct list of all scientific names from the points and
polygons table and queries that on the client. If this gets slow when as
the list of species gets bigger, we can move that query to the server. As
is, it is pretty fast. We'll need to experiment with how to do  quickly on
the server -- we don't want to be firing off select distinct queries on
every key press in the search field. Unless cached, select distinct is
pretty slow.
On Feb 14, 2012 7:53 PM, "Aaron Steele" <
reply@reply.github.com>
wrote:

**Comment by eightysteele** [comment]
Yeah, right now it's pretty fast, totally. When the list of names gets bigger, we can just store the uniques in App Engine and then surface an auto-complete web service. It will be pretty performant. We can setup a cron job that keeps the list of uniques in sync with CDB.

**Comment by eightysteele** [comment]
This issue is related to #58.

**Comment by eightysteele** [comment]
So our `names.js` hack is too slow on initial load (see #99). Time to move our auto-complete queries to the server. I'm going to implement this using a `ComputedProperty` via the NDB API or just store an index using `CacheItem` where multiple items represent a name where the key is `ac-{substring}`.
