### ISSUE TITLE
Deploying to App Engine failure

### ISSUE THREAD

**Issue by eightysteele** [MapofLife/MOL#47]
Deploying is failing on Python 2.7.2+, Ubuntu, SDK 1.6.1:

``` bash
Cloning 212 static files.
Cloned 100 files.
Cloned 200 files.
Cloning 25 application files.
Rolling back the update.
Error 400: --- begin server output ---
The POST body must be a newline delimited list of "path|hash" pairs.
--- end server output ---
```

**Comment by gaurav** [comment]
Confirmed on Python 2.6.1, MacOS X and on Ubuntu 10.04.3/Python 2.6.5/appcfg.py 1.6.1.

**Comment by eightysteele** [comment]
I submitted a question about this to the App Engine Google Group (waiting moderation) and also floated the same question to the #appengine IRC channel.

**Comment by eightysteele** [comment]
Resolved. There were some funky encoding issues in a file.
