### ISSUE TITLE
Initial hash load for loader.py duplication testing takes too long

### ISSUE THREAD

**Issue by gaurav** [MapofLife/MOL#48]
So I'm starting to see timeouts when downloading the list of hashes from CartoDB. We need some kind of cursor, ideally at the CartoDB API level, but if not, at the SQL level (i.e. using LIMIT and OFFSET to download the hashes). I'm marking this as priority, since this is holding up the rangemap upload.

**Comment by eightysteele** [comment]
Can you explain this more? What is the list of hashes and why are we downloading it from CartoDB?

**Comment by gaurav** [comment]
So the way loader.py implements idempotentcy right now is this: every feature is processed into a GeoJSON object, and then an SHA1 hash is generated for it (or more accurately, for a string representation of it generated by pprint). This hash is uploaded with the feature.

If the upload is interrupted for any reason, on the next runthrough, loader.py will download a list of all hashes associated with this source/collection combination. Then, once it's prepared a feature for upload, it just needs to check the hash to see if the feature has already been uploaded or not. This means that any change in the feature - whether in the geometry or the metadata - will cause the feature to be reuploaded, but a feature which hasn't changed (e.g. if only a few rows in a shapefile have been modified), then only the changed features will be uploaded. Note that this only works if the source/collection/filename combination stays the same -- if you're uploading a collection under a new name, for instance, this test will fail and your files will be reuploaded.

So right now, loader.py is failing because generating that initial list of hashes for download is running out of time on PostgreSQL. I'm going to try to use LIMIT and OFFSET to download the list in pieces; otherwise, I'll use EXPLAIN to try to figure out what's taking so long. In the worst case, I can reimplement this so that source/collection/filename/row combinations are unique, but then we lose out on the ability to edit individual features or rows in CSV files on the fly.

**Comment by gaurav** [comment]
Okay, this bug is causing problems for the GBIF upload. I tried rewriting loader.py to download the hashes 10,000 at a time instead of in one huge SELECT statement, but this requires ordering them, which seems to consistently go over the statement timeout limit, even when only pulling 10,000 hashes at a go. Doing a straight `SELECT *` causes an Internal Server Error (i.e. from the web server, not from PostgreSQL).

I can think of two ways to proceed from this point: we could try creating an index on FeatureHash to speed up ordering and retrieval of hashes, or I can write a script to figure out which rows have already been uploaded from the GBIF records and then tell loader.py to skip those many rows before upload. @eightysteele: Do you think it makes sense to try creating that index? It'll put a strain on the server for a while for sure, and will probably time out, but might be worth a shot. Otherwise, I'll go ahead with the skip-rows hack for now.

**Comment by eightysteele** [comment]
To deal with duplicates, I suggest we drop the hashing method and instead keep track of upload state using an SQLite db.

We can do this because polygons in a Shapefile are ordered. We can take advantage of that by keeping track of polygon numbers.

So, consider a simple db schema like this:

```
shapefile_name, cartodb_id, polygon_count, polygon_number
```

If the Puma concolor Shapefile had three polygons, the db would look like this after bulkloading without errors:

```
puma_concolor.shp, 1, 3, 0
puma_concolor.shp, 2, 3, 1
puma_concolor.shp, 3, 3, 2
```

Instead, suppose we run the bulkloader and the second polygon fails. Our db would look like this:

```
puma_concolor.shp, 1, 3, 0
puma_concolor.shp, 3, 3, 2
```

Now we run the bulkloader again, skip polygons that are in the db, and only upload the missing `polygon_number` 1.

This guards us against duplicates and makes the bulkloader fault tolerant.

Make sense?

**Comment by gaurav** [comment]
Okay, I'm working on this now. Is there any way we can reconcile getting the cartodb_id from the server with uploading 100 features at a go? I can't think of any way of making this work as a single SQL query, unless we use SELECT ... RETURNING to put those ids into a temporary table and download it from there. 

For now, I think I'll ignore the cartodb_id and just keep track of the rows in a file which have been uploaded. Does that sound okay?

**Comment by eightysteele** [comment]
For points, keeping track of rows is fine. For polygons, you'll need something like the SQLite solution above with exponential backoff and retries (see the email I sent you about this).

Also, FWIW, I'd use the `RETURNING` in conjunction with an `INSERT` (not with a `SELECT`): 

``` sql
INSERT INTO polygons (...) VALUES (...) RETURNING cartodb_id;
```

**Comment by gaurav** [comment]
My bad: I meant INSERT, not SELECT. Hmm, okay. At the moment, we're doing 

``` sql
BEGIN TRANSACTION; INSERT INTO polygons ...; INSERT INTO polygons ...; *repeat 100 times*; END TRANSACTION;
```

So I'm going to have to change this to 

``` sql
BEGIN TRANSACTION; INSERT INTO polygons (colNames) VALUES (a1, b1, c1, ...), (a2, b2, c2, ...) RETURNING cartodb_id; END TRANSACTION;
```

Right?

**Comment by eightysteele** [comment]
Not sure, so you'll have to play with it for a bit. Just run a leetle experiment using the SQL console on our CDB instance, and then post your results to this issue.

**Comment by gaurav** [comment]
Okay, so I decided to ignore cartodb_row_ids for now. The current algorithm for this process is:
1. Before preparing a feature (i.e. converting that feature into an SQL string), check to see if a local SQLite database has an entry corresponding to the source (or provider, as some parts of the source code still refers to it, see issue #7), collection, filename, and the name of the table we're uploading to, plus the row of the feature within that file (e.g. "blah.shp", row 110, or "blech.csv", row 1110291), with a status of "uploaded=1". If so, skip this feature; it's already been uploaded.
2. Once a feature has been prepared, its SQL string ("INSERT INTO ...") will be stored in a Python list. Its details will be entered into the SQLite database, but its status will be "uploaded=0". The SQLite rowid is stored in a list in memory.
3. Later, once 100 features (or 250, or whatever '-j' value is provided to loader.py) are ready for upload, they will all be uploaded as a single SQL statement ("BEGIN TRANSACTION; INSERT INTO ...; INSERT INTO ...; ... END TRANSACTION;"). At that point, we use the stored SQLite rowid to set "uploaded=1" for the newly uploaded rows.

This seems to be working for me (working code at https://github.com/mapofLife/MOL/tree/issue48).

**Comment by eightysteele** [comment]
> This seems to be working for me (working code at https://github.com/mapofLife/MOL/tree/issue48).

I think you got the link wrong to working code?

**Comment by gaurav** [comment]
Does it not work for you? Most of the relevant changes are in https://github.com/MapofLife/MOL/commit/ca542c0202425c88f673bf3e390ff530440c0800

**Comment by eightysteele** [comment]
Oops, my bad, the link works.

**Comment by eightysteele** [comment]
Closing issue. We're moving away from bulkloading over SQL API.
