### ISSUE TITLE
Add throttling for loader.py

### ISSUE THREAD

**Issue by gaurav** [MapofLife/MOL#49]
Simon Tokumine from Vizzuality suggests that throttling our upload rate might make the CartoDB UI more responsive for us. Probably the simplest way to do this would be to put in a few seconds "sleep" between consecutive SQL API calls. I'll work on this asap and see if it improves things.

**Comment by eightysteele** [comment]
Totally. Let's go with exponential backoff for the throttling implementation:

http://en.wikipedia.org/wiki/Exponential_backoff

Check out the App Engine bulkloader source code for a good example of this.

**Comment by gaurav** [comment]
Thanks for the tip! I will try this.

**Comment by eightysteele** [comment]
Excellent.

**Comment by eightysteele** [comment]
Closing issue since we're moving away from bulkloading over the SQL API.
