### ISSUE TITLE
Search index

### ISSUE THREAD

**Issue by eightysteele** [MapofLife/MOL#51]
Our search index rides on `scientificname` like this:

``` sql
CREATE INDEX sn_idx ON points USING gin(to_tsvector('english', scientificname))
CREATE INDEX sn_idx ON polygons USING gin(to_tsvector('english', scientificname))
```

Given a scientific name like `Lagenorhynchus cruciger`, we can search for it on `Lagenorhynchus` but not on the full scientific name. We need to be able to search on the full scientific name. 

More info:

http://www.postgresql.org/docs/9.1/static/textsearch.html

**Comment by gaurav** [comment]
Maybe we want to put another database table in front of the search? So a highly-indexed full-text fuzzy-logic-matching index of all the scientific names in the database, which maps said name back to "standard" names that the points and polygons table uses. This would also be useful for taxonomically clever searches (i.e. somebody searching for "Canidae" returns a list of all the canids in our dataset) as well as for species name verification (i.e. loader.py could warn people, "=Scientific name" is not in my list of scientific names; I'll still upload it, but err watch out).

**Comment by eightysteele** [comment]
Sounds good man. Want to create that table and we'll give it a try?

**Comment by eightysteele** [comment]
I'm actually thinking #53 would be a better solution here. Maybe?

**Comment by eightysteele** [comment]
We dropped ts_ type queries, so closing this in favor of #53.
