### ISSUE TITLE
Auto-complete names in search 

### ISSUE THREAD

**Issue by eightysteele** [MapofLife/MOL#58]
When searching, auto-complete typed in names.

**Comment by walterj** [comment]
Should apply to scientific and English names (and Family, Order?).

**Comment by eightysteele** [comment]
@jmalczyk, can you explain a little how you're implementing this feature? It will help me answer the question from @walterj about supporting family and order auto-completes.

**Comment by eightysteele** [comment]
Fixed in 4cb48d17f94c5e3ad652f4b541a125b8fa041404.

Auto-complete is for scientific name only. For supporting english names, family, and order, we need to add those to the MoL schema and update the polygons and points tables with the new column values. See #59 for details.

Closing issue.

**Comment by walterj** [comment]
Auto-complete should operate on the beginnings for words, not any text portion inside words. I.e. when typing 'Par', it should only search for Genus or Species names beginning with 'Par' (e.g. 'Parus'), not any occurrence of 'par' inside any word. This should also limit the total number of words assessed and returned.

**Comment by eightysteele** [comment]
Good catch. We're using the JQuery autocomplete plugin, and it supports passing a callback function as the autocomplete source (right now we're passing an array of scientific names). The callback would go here:

https://github.com/MapofLife/MOL/blob/develop/app/js/mol.map.search.js#L75

@jmalczyk, see this thread on SO for details on what the callback needs to do to support prefix matching:

http://stackoverflow.com/questions/2382497/jquery-autocomplete-plug-in-search-configuration

**Comment by eightysteele** [comment]
Re-opening issue. We're querying CartoDB for all distinct scientific names on app load. This query is taking too long. Auto-complete doesn't work until the query returns. @jmalczyk, let's chat about this offline. I think we can hack something quick for the short term, and then surface a longer term issue after end of month.

**Comment by walterj** [comment]
Sent example taxo table (with English and Family names etc) to Jeremy and Aaron.

**Comment by eightysteele** [comment]
Closed in 4aa81e0
