### ISSUE TITLE
English names in search

### ISSUE THREAD

**Issue by eightysteele** [MapofLife/MOL#59]
Support English names in search box.

**Comment by walterj** [comment]
Should we put heads together and develop a global taxonomy list with misc. fields (Class, Order, Family, English, Scientific, ..., IUCN status) that for now (beta release) may be static but later dynamic? It would be used for search, metadata (i.e. info about a species when mapped), and species list result annotation.

**Comment by eightysteele** [comment]
Well, so I think that all taxonomic information needs to be part of our MOL schema (instead of as a separate table) so that it's encoded directly with every point and polygon record. It should include Class, Order, Family, English, Scientific, IUCN status, and any other columns needed. @gaurav, are most of these columns already part of the MOL schema?

**Comment by walterj** [comment]
" ... encoded directly with every point and polygon record. It should include Class, Order, Family, English, Scientific, IUCN status, and any other columns needed ".

The limitation here is that some fields change with time. E.g. we may swap in/out taxonomies, or, most pertinently, want to update the IUCN status as it changes every year. We may want to add a field (e.g. Spanish name) down the road. What is the best way forward here? Perhaps best to discuss over skype.

**Comment by eightysteele** [comment]
> The limitation here is that some fields change with time.

Yeah, this is totally fine. I don't see this as a limitation since we can update taxonomy and IUCN columns using the CartoDB SQL API. So I think we're set here if we just add these columns to our schema. Good?

**Comment by gaurav** [comment]
I'll check this out tomorrow, but I don't think all those fields are in the schema yet, and putting them in after uploading the polygons might cause some headaches. I'll report back on this once I have a clearer idea on what's already uploaded, and how easy it might be to add in the data we need.

**Comment by walterj** [comment]
" uploading the polygons might cause some headaches."

If that is the case, we might require a different solution, as we will want to add and update select fields after upload.

-----Original Message-----

**Comment by eightysteele** [comment]
> putting them in after uploading the polygons might cause some headaches.

It will only be a headache now because we haven't extended loader.py to handle table updates yet. @gaurav, the easiest solution in the short term might be updating the schema, dropping the polygons table, and re-uploading them.

**Comment by gaurav** [comment]
@eightysteele: Yup, agreed.

**Comment by gaurav** [comment]
So the latest here is that we're waiting for @jmalczyk to get the taxonomic information from @walterj so we can figure out how to incorporate that. Right?

**Comment by walterj** [comment]
Sent to to @jmalczyk on Thursday. I think he has been working on it.

**Comment by eightysteele** [comment]
@gaurav - Yep. Once we get the English names, we'll store them in the `VernacularName` column in our schema. Make sense?

**Comment by gaurav** [comment]
Okay, great! Yes, VernacularName is definitely the right place to store them (unless there's a case where we have more than one vernacular name for a species, in which case ... maybe we can store them, semicolon-delimited, into the VernacularName field?). In any case, it looks like the right way to proceed might be:
1. Update vernacular names in mol_rangemaps and the new jetz/birds dataset.
2. Fix config.yaml in mol_rangemaps so it uses either SEASONAL or OccCode in setting Seasonality.
3. Upload the jetz/birds dataset from Yale (with any needed help from me).
4. Delete the bird rangemaps from mol_rangemaps.
5. Reupload mol_rangemaps (minus bird data, which is in another "collection" now, and with the fixed Seasonality)
6. Once that's done, we can move on to the long-languishing ecoregion/assemblance checklist data.

Sound good?

**Comment by eightysteele** [comment]
See the email that just went out which includes my thoughts on the above. @walter and @jmalczyk, are you seeing multiple English names for a species or no?

**Comment by walterj** [comment]
@walter and @jmalczyk, are you seeing multiple English names for a species or no?

Do you mean whether we would like to upload and have in CartoDB multiple English names per species? Not at this point I would say. Later we may add such fields as 'Alternate name' or 'Spanish name' etc., but not for first release for sure!
Does this answer the question?

**Comment by eightysteele** [comment]
@walterj - Yeah man, that answers it! Awesome.
