### ISSUE TITLE
Update website content and add Google Analytics code to each page

### ISSUE THREAD

**Issue by gaurav** [MapofLife/MOL#6]
We need to update website content (to add me!), and to add Google Analytics to the standard template to track people visiting mappinglife.org.

**Comment by eightysteele** [comment]
@gaurav: Is this done?

**Comment by gaurav** [comment]
Thanks for the reminder! This is done as of @4b9280562b. I'll close this bug once I've confirmed that the analytics code is actually collecting data.

**Comment by gaurav** [comment]
Okay, this seems to be working okay. Rob, Walter, Aaron and Tuco should all have access to the Analytics page now. Closing.
