### ISSUE TITLE
Fold in assemblage checklists and ecoregions 

### ISSUE THREAD

**Issue by eightysteele** [MapofLife/MOL#66]
Need to bring back our AC and ER, woot.

**Comment by walterj** [comment]
From previous document: 
(Multi-)Polygonal species lists (single shapefile upload, one file = many species)
- Examples: ecoregional species lists (polygons adjacent),  country species lists, reserve(s) or study area(s) species lists, island checklists, plant survey plots, atlas grids or transect polygons species lists.
- Provider has one shapefile with many polygons in which each GeoObject, i.e. polygon, (identified with unique AreaID in dbf) represents one study area (ecoregion, park, survey area). Note that sometimes the study area (same AreaID) may spread over several polygons (e.g. some disjointed ecoregions).
- Format is ESRI shapefile. Projection is defined in .prj. We could (but may not need/want to) enforce for it to always be ‘geographic, WGS 1984’.
- Provider at some point in upload or metadata process needs to identify the (numerical) field in the shapefile dbf that contains the unique AreaID that then links to the species data.
- Provider uploads one separate .csv file in which every row represents a combination of an AreaID and a species name. Additional fields (columns) indicate the type of presence (categorical: invasive, winter-only, uncertain etc) as for species range maps, or abundance. This table is essentially like a combination of .dbf files of range map type above, and should be treated the same way.

**Comment by eightysteele** [comment]
@walterj: Thanks for the background info on this.

**Comment by gaurav** [comment]
It sounds like there's consensus on combining the shapefiles and the CSV file into a set of shapefiles with species information, which can then be uploaded by loader.py without any modification. @eightysteele, does that sound good? If so, I'll proceed on this.
