### ISSUE TITLE
Which 'provider' should we use?

### ISSUE THREAD

**Issue by gaurav** [MapofLife/MOL#7]
A quick question. We have three options which we can use to determine the 'provider' in our database:
1. config.yaml currently has a 'Source' section, which isn't really used for anything. We could use the 'name' section of that.
2. We could add 'provider' as a required field to config.yaml.
3. We could use the directory name ('iucn', 'jetz', etc.)

Any votes on which one we should use? So far, we've mostly used the directory name, but now we're going to start loading larger datasets, it makes sense that we shouldn't be so dependent on where the files are present. If the 'Source' section of config.yaml isn't being used for anything, it might make more sense to create a 'provider' required field in the Field Specification on Fusion Table and use that.

I vote for option 2, and will implement that if there isn't any major opposition before Wednesday.

**Comment by eightysteele** [comment]
@gaurav: I think the terminology that we've been using for "provider" is "source". Can we modify loader.py and config.yaml and FT to use "source" instead of "provider"?

**Comment by eightysteele** [comment]
Bump. Where are we at on this one?
