### ISSUE TITLE
Layer opacity slider

### ISSUE THREAD

**Issue by eightysteele** [MapofLife/MOL#72]
Add a opacity slider to the layer widget using an HTML5 range slider element:

`<input type="range" name="opacity" min="1" max="100" step="25" />`

We should have a course `step`, like 25. When the slider event fires, we'll need to remove the layer tiles from the map, and then add them back using the new opacity values (converted to something between 0 and 1.0) in the `ImageMapTypeOptions`. See:

http://code.google.com/apis/maps/documentation/javascript/reference.html#ImageMapTypeOptions

Note that this will likely require a simple patch to the CartoCSS JS library, allowing us to pass in the layer opacity value. It will be a patch similar to this one that passed through the layer name value:

https://github.com/eightysteele/cartodb-gmapsv3/commit/5f6ef57e9b5b5a3bca2769111c619740438f2b86

**Comment by eightysteele** [comment]
Re-working the layer widget to accommodate opacity slider, toggle (t), zoom (z), and info (i):

![](http://i.imgur.com/bX78A.png)

**Comment by walterj** [comment]
Looks nice! Look forward to testing this

**Comment by eightysteele** [comment]
> Looks nice! Look forward to testing this

Thanks man, look for an update email later tonight with a demo and a link.
