### ISSUE TITLE
Fold in EE species list functionality

### ISSUE THREAD

**Issue by eightysteele** [MapofLife/MOL#75]
Basically let the user draw a polygon and then view the species list.

**Comment by walterj** [comment]
Tentative thoughts on this:

User can move pointer with circle size of ca. 100km and click do get ‘point’ list produced, or with same pointer can draw polygon to produce ‘area’ list (behind the scenes, that polygon would need to be buffered out by ca. 100km to address expert map boundary uncertainty). Then user gets in window a structured response that has as title the Class/Order(s) selected, the area (including buffer) queried, the count of species, and then, in taxonomic structure/order, the species in English. This will require joining results with a taxonomy table that we will need to add. 
Ideal:  Upon pushing a button, users can then select one to several additional columns for output: Class, Order, Latin, taxonomy used etc.. These can be displayed or downloaded as csv. User can change taxon selection by clicking on taxon list (bottom left), gets taken back to taxon selection window.

**Comment by eightysteele** [comment]
Nice. 

So as a first step, I think we can pretty quickly support a response that includes the class/order(s) selected, the area with buffer queried, and a species count.

After that, we can fold in the English names (since we don't have that yet, but see #59).

Then finally we revisit the idea of exporting CSV, changing taxon selection, etc.

**Comment by eightysteele** [comment]
Fixed as of 26a933daca905cfc902dc8fb0e1fd1512dd33a2a
