### ISSUE TITLE
Modify loader.py to include type (range, protected area, ecoregion)

### ISSUE THREAD

**Issue by eightysteele** [MapofLife/MOL#9]
This is needed in the UI for filtering on type.

**Comment by eightysteele** [comment]
Ok, I see that `type` is in config.yaml, but we need standardized names maybe?

range
ecoregion
protectedarea

**Comment by gaurav** [comment]
I think it's safe to "make up a spec" for now, maybe even just in this comment thread, by linking back to your comment on this issue when you use that term in the code. At some point we need to make a big push for controlled vocabularies; once we make it through this bit of development (integration + analyses workflow), maybe I'll "peel off" and go work on that in mid-November or so, depending on other tasks that need to be done?

Previous discussion: https://github.com/andrewxhill/MOL/issues/108

**Comment by gaurav** [comment]
Adding one more: "pointoccurrence", for point occurence data.

**Comment by eightysteele** [comment]
+1

**Comment by gaurav** [comment]
Okay, let's try to fix this once and for all. I'm going to try to use @tucotuco's suggestion in https://github.com/andrewxhill/MOL/issues/108. Note that this is a validation-only step: the database will allow any values for any field.

**Comment by eightysteele** [comment]
Yeah, let's keep this simple to start. I think we can just add type to the config file. Right? We have range, ecoregion, protectedarea, and occurrencepoints. It's something that providers will specify in the config. Maybe?

**Comment by gaurav** [comment]
How do you mean, in the config? The suggestion I linked to above was to have a Fusion Table containing a set of possible values - with user-friendly definitions, names, or any other details. It shouldn't take too long to sort out - the hardest bit will be communicating with the Fusion Table. We'd also need to signal that a field is constrainted, maybe by setting it's type to 'ConstrainedText' in the field spec fusion table. I started work on this yesterday, and there's only a couple of hours of work left on it.

**Comment by gaurav** [comment]
Okay, I've got this working in theory on branch 'issue9'! Very barely tested, but it's a start! I'll test it more thoroughly in the next few days, and especially once we get POST to CartoDB working. I'll e-mail everybody a link to the Fusion Table tomorrow.

**Comment by eightysteele** [comment]
@gaurav, can we modify the bulkloader so that the `type` column is one of:

```
points
range 
ecoregion
protectedarea
```

**Comment by gaurav** [comment]
I've created issue #103 to handle the general case (i.e. controlled vocabularies in fields apart from `type`). The specific case (for `type`) has been fixed in @f3d3de866c8a0. Since that's done, I'll close this issue.
