### ISSUE TITLE
Layer opacity change changes layer order

### ISSUE THREAD

**Issue by eightysteele** [MapofLife/MOL#98]
Search for `Dacelo novaeguineae` and add both layers on the map. Drag the polygon layer to the top. Change the layer opacity by dragging slider. The polygon layer, even though it's widget is on the top, gets rendered below the points.

**Comment by gaurav** [comment]
In some cases, it does the right thing, but if you flip the polygon and point datasets, you do see this bug sometimes.

**Comment by gaurav** [comment]
Also observed in 'Parotomys brantsii'.

**Comment by eightysteele** [comment]
Yep, it's a general problem not specific to a species.

**Comment by gaurav** [comment]
Here's my steps-to-reproduce:
1. When setting up your testing instance, make sure you have a species which has a GBIF points map as well as a rangemap (I'm using "Parotomys brantsii" for testing).
2. Add both the points and polygon maps by searching for the species (by scientific or common name).
3. Switch the layers in the UI on the upper right corner until range maps is "above" (i.e. closer to the top of the screen) than the points map. The points should now be visible through the range map.
4. Reduce the opacity of the polygons layer.

Expected: the points are visible through the polygons layer.
Obtained: once the opacity is changed, the points are drawn on top of the polygons layer. They remain in this state until the polygon layer is next moved above the points layer.
